### ISSUE TITLE
Internal Server Error when attempting to view snippets after upgrade to 4.21.0

### ISSUE THREAD

**Issue by axb21** [gitbucket/gitbucket#1858]
## Issue
**Impacted version**: 4.21.0

**Deployment mode**: standalone app

**Problem description**:
I upgraded gitbucket from v4.20.0, which appeared to work normally including snippets, to v4.21.0 by replacing the 4.20.0 war file with the 4.21.0 one downloadable from github. After restarting, I am given an Internal Server Error when I attempt to view my snippets. The specific error is:

```Internal Server Error
java.lang.NoSuchMethodError: gitbucket.core.util.JGitUtil$.getFileList(Lorg/eclipse/jgit/api/Git;Ljava/lang/String;Ljava/lang/String;)Lscala/collection/immutable/List;```

My expectation is to see my list of snippets.

The latest version of the gist plugin appears to be 4.11.0 at the time of this writing, which is what I have installed.

**Comment by takezoe** [comment]
Oops, we had to update gist-plugin for GitBucket 4.21.0. I uploaded a new version of gist-plugin. Could you use it instead of the bundled version?
https://github.com/gitbucket/gitbucket-gist-plugin/releases/tag/4.12.0

**Comment by takezoe** [comment]
In addition, I will release 4.21.1 with new gist-plugin as soon as possible.

**Comment by axb21** [comment]
Thank you. Upgrading the gist plugin corrected the problem!

**Comment by keides2** [comment]
Hi,
I'm getting an error with v4.20.0 below.
Can I use the v4.21.1 plug-in?

Error:
```
Internal Server Error
java.lang.NullPointerException
```
Thank you,
